### ISSUE TITLE
auto-indentation broken

### ISSUE THREAD

**Issue by FunTimeCoding** [saltstack/salt-vim#11] opened 2013-08-30 15:02 UTC
when indenting using gg=G, the indentation does what its documented to do.

Every ':' the new line gets indented two more spaces. the problem is it never goes back.

```
base:
  'host1':
    - services.apache
    'host2':
      - services.apache
```

..it just never removes the two spaces again when it should.

**Comment by gravyboat** [comment] 2015-05-13 19:20
@whiteinge Is this still an issue? It's been quite a while and I'm not sure if someone addressed it.

**Comment by whiteinge** [comment] 2015-05-13 20:07
This is indeed still a thing.

**Comment by basepi** [comment] 2015-05-13 20:38
Behavior is still there. The problem is that this particular parsing is a bit difficult -- we can't just de-indent on `:`, because sometimes we want `:` with no change in indent (if we're doing multiple keyword arguments, for example). I've never written vim indent files, but we would have to be able to look back at the previous line and see whether it begins in a `- ` or not.

**Comment by nacho-milanese** [comment] 2015-08-28 00:28
I fixed the bug for all the examples I tried with, but I was unable to push the code.
As it's the first time I collaborate in someone else's code, I don't know what would be the best method to share my code with you

**Comment by gravyboat** [comment] 2015-08-28 00:31
@nacho-milanese, Awesome! So you'd want to fork the repo (https://help.github.com/articles/fork-a-repo/), commit your code to your copy of the repo (the fork), then make a pull request against this repo which will automatically create an issue that we'll review and submit feedback on if needed, then merge back into the master branch. The document I linked explains all the steps (or has links to them) regarding how to fork, push your code, and create the PR depending on your familiarity with Git. If you run into any problems feel free to add a comment, otherwise we'll see you in the Pull Request!

**Comment by nacho-milanese** [comment] 2015-08-28 01:01
Thanks @gravyboat Pull Request done.
Tested against several salt .sls examples and it seems to fix the issue

**Comment by whiteinge** [comment] 2015-08-28 02:03
#37 is merged. Works like a charm! :smile:

**Closed** 2015-08-28 02:03 UTC
Labels: bug

**Comment by gravyboat** [comment] 2015-08-28 05:11
@nacho-milanese Awesome thanks a bunch!
